[build-system]
requires = ["setuptools>=61.0,<81"]
build-backend = "setuptools.build_meta"

[project]
name = "spatioev"
version = "0.1.0"
description = "Spatial feature extraction and spatial evolution framework for multiplexed imaging"
authors = [
    { name = "Shihong Wu, Sakina Amin, Rachael Bashford-Rogers" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    # "numpy",
    # "pandas",
    # "scipy",
    # "matplotlib",
    # "seaborn",
    # "anndata",
    # "scikit-image",
    # "scanpy",
    "scimap[napari]",
    "zarr<3",
    "numcodecs<0.16",
    "igraph",
    "leidenalg"
]

[project.optional-dependencies]

scverse = [
    "squidpy",
    "spatialdata"
]

dev = [
    "pytest",
    "black",
    "ruff"
]

[tool.setuptools.packages.find]
include = ["spatioev*"]